name: Deploy

on:
  workflow_dispatch:

env:
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  PACT_SERVICE_VERSION: 1.0.0
  PACT_SERVICE_TAG: dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install pact
      run: make install

    - name: Can I Deploy
      run: |
        pact/bin/pact-broker can-i-deploy \
          --pacticipant TestConsumer \
          --broker-base-url https://hb-test.pactflow.io \
          --broker-token $PACT_BROKER_TOKEN \
          --latest

    - name: Run consumer contract tests
      run: make consumer-pact

    - name: Publish contrats with tag
      run: make publish
